# -*- coding: utf-8 -*-
"""Real-Time Object Detection Dashboard

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o3OR4VeCzokBLLmhDBl_dThg6i_3XQrR
"""

import cv2
import streamlit as st
from ultralytics import YOLO
import tempfile

st.title("Real-Time Object Detection Dashboard")

model = YOLO("yolov8n.pt")  # small YOLOv8 model for demo

uploaded_file = st.file_uploader("Upload a video file", type=["mp4", "mov", "avi"])

if uploaded_file:
    tfile = tempfile.NamedTemporaryFile(delete=False)
    tfile.write(uploaded_file.read())
    video_path = tfile.name

    cap = cv2.VideoCapture(video_path)
    frame_window = st.image([])

    while cap.isOpened():
        ret, frame = cap.read()
        if not ret:
            break
        results = model(frame)[0]
        annotated_frame = results.plot()
        frame_window.image(cv2.cvtColor(annotated_frame, cv2.COLOR_BGR2RGB))

    cap.release()